// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpvoiioqctsdyptwtpzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdm9paW9xY3RzZHlwdHd0cHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzk0NjksImV4cCI6MjA1OTgxNTQ2OX0.jR-9_Izx78VWXl7RJEy_o4XuXIpURIoanH8s3FDBCcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);